version: '3.8'

services:
  # --- Service de Base de Données (MySQL) ---
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=la_brute
    volumes:
      - ./app_brute_bdd.sql:/docker-entrypoint-initdb.d/app_brute_bdd.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  # --- Service de l'Application (Node.js) ---
  app-labrute:
    build: .
    command: sh -c "sleep 10 && npm start"
    ports:
      - "80:4200"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=la_brute
    depends_on:
      db:
        condition: service_healthy